{
  imports = [
    ./colorizer.nix
    ./autopairs.nix
    ./cmp.nix
    ./coq.nix
    ./lsp.nix
    ./lualine.nix
    ./barbar.nix
    ./startup.nix
    ./conform.nix
    ./icons.nix
    ./which-key.nix
    ./telescope.nix
    ./treesitter.nix
    ./rust.nix
    ./oil.nix
  ];
}
